name: Deploy with kubectl

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

# Define the jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 3: Verify kubectl installation
      - name: Verify kubectl version
        run: kubectl version --client

      # Step 4: Set up kubeconfig
      - name: Set up kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      # Step 5: Deploy to Kubernetes
      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./k8s-manifests/

      # Step 6: Verify deployment status
      - name: Check deployment status
        run: kubectl rollout status deployment/<deployment-name> -n <namespace>
